### ISSUE TITLE
Defer initialisation logging messages

### ISSUE THREAD

**Issue by SamTebbs33** [SamTebbs33/pluto#115]
It would be nice to use Zig's `defer` when printing at the end of each initialisation function. See @DrDeano 's comment [here](https://github.com/SamTebbs33/pluto/pull/104#discussion_r360519276) for context.

**Comment by DrDeano** [comment]
We will need to make sure to handle the case when runtime tests are active as `derfer` will be called after the runtime tests. Maybe we could change the python test cases to get around this where we would have the `init` then `runtime tests`, then the `done`.
