### ISSUE TITLE
Runtime testing framework

### ISSUE THREAD

**Issue by SamTebbs33** [SamTebbs33/pluto#12]
It would be useful to implement a system for testing the kernel at runtime. This would be used to test components of the kernel, such as paging, multitasking and the filesystem.

A possible approach to running a certain testcase would be to boot the kernel in testing mode (perhaps with a build specific for that testcase), have it initialise the component being tested and printing to serial with some predetermined format based on success or failure. A program could then be attached to the kernel's serial port ensuring that the correct output is received.

The results could then be compiled into a testing report.

Possible dependency on #37 if serial output is how we monitor test results.

**Comment by SamTebbs33** [comment]
https://wiki.osdev.org/Unit_Testing

**Comment by SamTebbs33** [comment]
https://forum.osdev.org/viewtopic.php?t=17948

**Comment by DrDeano** [comment]
Not sure if we have the money for that ;)

**Comment by SamTebbs33** [comment]
Didn't stop me buying an core 2 duo laptop from 2006 😂 £10 well spent

**Comment by SamTebbs33** [comment]
I've been exploring our options with this. My current design ideas are as follows:

When you want to do a runtime test of the kernel, you build it with `zig build -Drt-test=true` which then sets a flag in build.zig and builds as normal. The source files will check for that flag in the build file (using `@build' to refer to it) and add some logging specific to testing if the flag is set. The new build can be tested with `zig build test -Drt-test=true`, which will run a test harness. This test harness will run `zig build run` and attach itself to the emulators stdout so that it can capture the serial output. The test harness will then check the output to make sure all test logs are emitted and are correct. The results are then printed in a readable way.
