### ISSUE TITLE
Add configuration to build for cpu model

### ISSUE THREAD

**Issue by DrDeano** [SamTebbs33/pluto#129]
When building, add options for changing the CPU model.

```Zig
const target = CrossTarget{
        .cpu_arch = .i386,
        .os_tag = .freestanding,
        .cpu_model = .{ .explicit = &Target.x86.cpu._i686 },
    };
```

Where changing ` .cpu_model = .{ .explicit = &Target.x86.cpu.<MODEL> },`

With have to think about this and the best way of doing it without having hundards of options

**Comment by SamTebbs33** [comment]
Good idea. I reckon we could have a simple `-Dcpu=cpu_name` option and parse that to something we can use for `cpu_features` in Target.

**Comment by DrDeano** [comment]
This can be done using `b.standardTargetOptions()`
