### ISSUE TITLE
Pass the boot payload to serial.init

### ISSUE THREAD

**Issue by SamTebbs33** [SamTebbs33/pluto#158]
The aarch64 port, for example, needs the boot payload to be passed to the serial initialiser.

**Comment by DrDeano** [comment]
Why is this the case?

**Comment by SamTebbs33** [comment]
> Why is this the case?

Serial is done via memory mapped I/O and the address used for that depends on information in the boot payload.

**Comment by DrDeano** [comment]
I see :), Just wandering
