### ISSUE TITLE
Fork of branch develop is failing to build

### ISSUE THREAD

**Issue by markfirmware** [SamTebbs33/pluto#165]
https://github.com/markfirmware/pluto/runs/789310528?check_suite_focus=true

I believe my develop branch is identical to yours.

**Comment by SamTebbs33** [comment]
I believe this is due to changes in `zig fmt`. We're seeing it in this repo as well.

**Comment by DrDeano** [comment]
I have made a PR for zig to fix this: https://github.com/ziglang/zig/pull/5648, once/if merged, this will be fixed
