### ISSUE TITLE
On a linode.com x64 debian 10, zig build test will crash

### ISSUE THREAD

**Issue by markfirmware** [SamTebbs33/pluto#171]
The following command terminated unexpectedly:
    /root/github.com/samtebbs33/pluto/tools/zig/zig test /root/github.com/samtebbs33/pluto/src/kernel/kmain.zig --pkg-begin build_options /root/github.com/samtebbs33/pluto/zig-cache/test_build_options.zig --pkg-end --cache-dir /root/github.com/samtebbs33/pluto/zig-cache --name test -target i386-native --test-cmd qemu-i386 --test-cmd-bin --pkg-begin constants /root/github.com/samtebbs33/pluto/src/kernel/arch/x86/constants.zig --pkg-end --main-pkg-path /root/github.com/samtebbs33/pluto 
    
    Build failed. The following command failed:
    /root/github.com/samtebbs33/pluto/zig-cache/o/snfaRyDmoqYNSEMGK4g2J0tNP9wpqpqK5IiebregQN9EGFhQLSsJKtO5rKiuYr1X/build /root/github.com/samtebbs33/pluto/tools/zig/zig /root/github.com/samtebbs33/pluto /root/github.com/samtebbs33/pluto/zig-cache test

I isolated it to test Allocator - if removed then 179 tests pass. I think the 4MB stack frame is the problem. I tried changing it to 4KB and got the following test failures report.

I do not yet have any suggestion for handling this. Regards, Mark.

    1/180 src.kernel.arch.test ""...OK
    2/180 src.kernel.pmm.test "alloc"...OK
    3/180 src.kernel.pmm.test "free"...OK
    4/180 src.kernel.pmm.test "setAddr and isSet"...OK
    5/180 src.kernel.heap.test "init errors on non-power-of-two"...OK
    6/180 src.kernel.heap.test "free detects unallocated addresses"...OK
    7/180 src.kernel.heap.test "whole heap can be allocated and freed"...OK
    8/180 src.kernel.heap.test "Allocator"...error: OutOfMemory
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:90:9: 0x42c195 in src.kernel.heap.Heap.realloc (test)
            return Allocator.Error.OutOfMemory;
            ^
    /root/github.com/samtebbs33/pluto/tools/zig/lib/zig/std/mem.zig:164:28: 0x460bae in std.mem.Allocator.alignedAlloc (test)
            const byte_slice = try self.reallocFn(self, &[0]u8{}, undefined, byte_count, a);
                               ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:425:17: 0x45d712 in src.kernel.heap.testAllocatorLargeAlignment (test)
        var slice = try allocator.alignedAlloc(u8, large_align, 500);
                    ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:343:5: 0x419510 in src.kernel.heap.test "Allocator" (test)
        try testAllocatorLargeAlignment(allocator);
        ^
    /root/github.com/samtebbs33/pluto/tools/zig/lib/zig/std/special/test_runner.zig:65:17: 0x44dd76 in std.special.main (test)
                    return err;
                    ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    /root/github.com/samtebbs33/pluto/src/kernel/heap.zig:208:13: 0x444262 in src.kernel.heap.Heap.free (test)
                return Error.NotAllocated;
                ^
    
    Tests failed. Use the following command to reproduce the failure:
    /root/github.com/samtebbs33/pluto/zig-cache/o/ZgyqyK6yo7ZB4mNctHnc2pFKYLyyrN4SXWUzJ_vELX6De5zbn6XBlF2E-3md3yxo/test
    The following command exited with error code 1:
    /root/github.com/samtebbs33/pluto/tools/zig/zig test /root/github.com/samtebbs33/pluto/src/kernel/kmain.zig --pkg-begin build_options /root/github.com/samtebbs33/pluto/zig-cache/test_build_options.zig --pkg-end --cache-dir /root/github.com/samtebbs33/pluto/zig-cache --name test -target i386-native --test-cmd qemu-i386 --test-cmd-bin --pkg-begin constants /root/github.com/samtebbs33/pluto/src/kernel/arch/x86/constants.zig --pkg-end --main-pkg-path /root/github.com/samtebbs33/pluto 
    
    Build failed. The following command failed:
    /root/github.com/samtebbs33/pluto/zig-cache/o/snfaRyDmoqYNSEMGK4g2J0tNP9wpqpqK5IiebregQN9EGFhQLSsJKtO5rKiuYr1X/build /root/github.com/samtebbs33/pluto/tools/zig/zig /root/github.com/samtebbs33/pluto /root/github.com/samtebbs33/pluto/zig-cache test

**Comment by SamTebbs33** [comment]
Thanks for the report. Unfortunately this isn't really something we can reproduce since linode seems to be a paid service. If you figure out the issue we'd be happy to merge a fix to stop this from happening!

**Comment by markfirmware** [comment]
Ok, I just tried 2MB instead and all 180 tests pass. I will open a ticket on zig to explore the stack frame size crashing the compiler.

**Comment by SamTebbs33** [comment]
Excellent. Please do link the zig issue here and I'll mark this issue as externally blocked.

**Comment by markfirmware** [comment]
Thanks. I will get to this later today.

**Comment by markfirmware** [comment]
FYI this is due to a a 1GB host - it does not occur on a 4GB host. Not yet completely closed.

**Comment by markfirmware** [comment]
Using a host with too small a memory is noted in https://github.com/ziglang/zig/issues/5687
