### ISSUE TITLE
Is this expected for successful build rt-test ?

### ISSUE THREAD

**Issue by markfirmware** [SamTebbs33/pluto#172]
xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.
    
    Drive current: -outdev 'stdio:zig-cache/bin/pluto.iso'
    Media current: stdio file, overwriteable
    Media status : is blank
    Media summary: 0 sessions, 0 data blocks, 0 data,  341g free
    Added to ISO image: directory '/'='/tmp/grub.wc026Y'
    xorriso : UPDATE :       3 files added in 1 seconds
    Added to ISO image: directory '/'='/workspace/pluto/zig-cache/bin/iso'
    xorriso : UPDATE :      10 files added in 1 seconds
    ISO image produced: 510 sectors
    Written to medium : 510 sectors at LBA 0
    Writing to 'stdio:zig-cache/bin/pluto.iso' completed successfully.
    
    qemu-system-i386: terminating on signal 15 from pid 6410 (/workspace/pluto/zig-cache/o/sryw0ok8WIhW3OfK9PEbme50-0VNLUMX7wKpQJYpYecJCvd74YUo9_GAyLQ5IMT7/build)

**Comment by SamTebbs33** [comment]
I don't believe so since it should show the log messages. What command are you running?

**Comment by markfirmware** [comment]
Trying zig build rt-test in a gitpod workspace #173.
