### ISSUE TITLE
Create basic bootable kernel for x86

### ISSUE THREAD

**Issue by SamTebbs33** [SamTebbs33/pluto#3]
We need a basic bootable kernel for x86. This can be imported from my [previous kernel](https://github.com/SamTebbs33/jaq) but with the relevant conversions to Zig ([Andre Kelley's video](https://www.youtube.com/watch?v=yUge-ujPxzQ) on this will be helpful when it comes to the language's intricacies).

This work will include making a master Makefile that will also make the chosen architecture's bootloader.

A discussion point is whether or not the kernel should be in the higher half (with addresses starting at 3GiB + 1MiB) from the very start. I think it should as it makes mapping the kernel into user processes easier, and means you don't have to relocate an executable's code up to the higher half later on.

**Comment by SamTebbs33** [comment]
@DrDeano What do you think about it being in the higher half from the start?

**Comment by DrDeano** [comment]
@SamTebbs33 We should have a higher half, more advantages than disadvantages.
