### ISSUE TITLE
Print stack trace when kernel panic

### ISSUE THREAD

**Issue by DrDeano** [SamTebbs33/pluto#44]
Here is one example:
https://andrewkelley.me/post/zig-stack-traces-kernel-panic-bare-bones-os.html

**Comment by SamTebbs33** [comment]
Good idea. We should decide upon whether this should be logged to serial or the screen. I vote for serial.

**Comment by SamTebbs33** [comment]
Including the debug info explicitly from the link script triples the size of each section and the resulting binary. This issue is blocked on figuring out why that is.

**Comment by SamTebbs33** [comment]
grub doesn't load the debug info sections from the elf into memory, so the current plan is to insert them into the binary at build time.
