### ISSUE TITLE
Add a testing framwork around arch_mock.zig

### ISSUE THREAD

**Issue by DrDeano** [SamTebbs33/pluto#45]
Have the ability to test input values from called to arch specific functions like outb. There should be an init function to set up the testing for arch_mock which the user will provide a list of values to be expected. Then each call to the mocked arch function will test the parameters in order. The user will need to know how many calls will be made and the number of parameters that will be expected to be passed. And more or less should fail the test. Any parameters that don't match should fail the test.

**Comment by SamTebbs33** [comment]
Is this going to be for making the testing of functions more uniform, something like this?
```
Case = {
    name: string,
    function: func,
    parameters: list,
    expected: value
}

fn foo(a: u32, b: u32) { return a + b; }

cases = {
    Case { "foo works with negative numbers", foo, (-1, -3), -4 },
    Case { "foo works with positive numbers", foo, (3, 6), 9 },
    ...
}

for (cases) |case| {
    if (case.func(case.parameters) != case.expected)
        error(case.name);
}
```

**Comment by DrDeano** [comment]
Its going to more for testing parameters of functions that are more arch specific as you can't do a OUT instruction in user mode and so u can simulate the IN instruction to return expected and unexpected results so to test error handling

**Comment by SamTebbs33** [comment]
Ah ok, makes sense
