### ISSUE TITLE
Add some extensive x86 runtime tests

### ISSUE THREAD

**Issue by SamTebbs33** [SamTebbs33/pluto#60]
Once #59 is done, we can add some extensive runtime tests for x86 that we wouldn't want to run in a normal build.

- [x] [Syscalls](https://github.com/SamTebbs33/pluto/pull/56)
- [x] [Paging](https://github.com/SamTebbs33/pluto/pull/73)
- [x] [IRQs](https://github.com/SamTebbs33/pluto/pull/92) and [ISRs](https://github.com/SamTebbs33/pluto/pull/93)
- [x] [PIC](https://github.com/SamTebbs33/pluto/pull/94)
- [x] PIT

This work could be split as the person who implemented the features above is probably best suited to testing it.

Depends on #59

**Comment by SamTebbs33** [comment]
It would also be good to add a TEST log level to differentiate them from normal log messages.

**Comment by DrDeano** [comment]
I was thinking of this, but will need to hide this from the real build. Maybe add it to the log_mock.zig once #45 is done. But idk if added a TEST log level will be necessary as you can just use INFO or DEBUG.

**Comment by SamTebbs33** [comment]
> I was thinking of this, but will need to hide this from the real build.

As in only expose the TEST level to code if we're doing an rt test?

> Maybe add it to the log_mock.zig once #45 is done. But idk if added a TEST log level will be necessary as you can just use INFO or DEBUG.

That's true, we could always add one later on if we feel the need to differentiate. My only thinking was that it would make scanning through logs easier.

**Comment by DrDeano** [comment]
Yes, only expose TEST to rt_test, but will add a lot of testing logs to the code base.
It would be easier maybe but will have to change all logging to include testing logs where could just use DEBUG.

**Comment by SamTebbs33** [comment]
I forgot about the PIT
