### ISSUE TITLE
Decide on a coding style standard

### ISSUE THREAD

**Issue by BrandonTJones** [SamTebbs33/pluto#61]
This will make the code clean and consistent. Once a style is decided 2 things need to be done:

- A checker should be added to CI with a failure returned if it isn't up to standard.

- A linter script should be added to the repository so any developer can check a commit before pushing with a mistake.

**Comment by SamTebbs33** [comment]
Agreed. With zig being a young language there aren't many established styles out there, but we could inherit one from C and adapt it as required.

**Comment by SamTebbs33** [comment]
I vote for the [K&R}(https://en.wikipedia.org/wiki/Indentation_style#K&R_style) style but with braces on the same line as the function signature. In addition, there's shouldn't be any trailing whitespace and indentation uses blocks of 4 spaces.

**Comment by DrDeano** [comment]
In addition, globals have types and locals don't.
For the order of stuff, i will suggest:
- imports
- types (not global then global)
- consts (normal consts like defines if in C then enums then structs)
- global consts (normal consts then enums then structs)
- vars
- global vars
- inline fn
- fn
- pub fn
- entry/init fn

Some ordering could be discuses as structs and enums could be considered as types so could have:
- imports
- types (not global then global)
- const enum then struct
- global consts enum then struct
- consts (normal consts like defines if in C)
- global consts (normal consts)
- Then the rest

Could have globals first?

Max 100 character lines
Align the const values e.g.
const OCW2_INTERRUPT_LEVEL_1: u8 = 0x01;
const OCW2_INTERRUPT_LEVEL_2: u8 = 0x02;
const OCW2_INTERRUPT_LEVEL_3: u8 = 0x04;
const OCW2_END_OF_INTERRUPT: u8 = 0x20;
const OCW2_SELECTION: u8               = 0x40;
const OCW2_ROTATION: u8                = 0x80;

In addition, there should be any trailing whitespace for indentation.

I think this will do for now, if there are an i have missed...

**Comment by BrandonTJones** [comment]
> I vote for the [K&R](https://en.wikipedia.org/wiki/Indentation_style#K&R_style) style but with braces on the same line as the function signature. In addition, there shouldn't be any trailing whitespace and indentation uses blocks of 4 spaces.

space seperating the brace on the function sig line or not? This rule should then apply to structs etc. too

**Comment by SamTebbs33** [comment]
Yep, space separating the brace and function signature

**Comment by SamTebbs33** [comment]
I agree with the ordering suggestions, with the only point of consideration being that it could be good to have public types and constants above non-public types and constants, so that someone using the API can easily see what is available. I'm not too bothered either way though.

An idea I just had was to accept the style mandated by `zig fmt`, as that would make it easy for us to fix style issues (just run `zig fmt` on a file), easy to check if any files are non-conforming (we should do so in CI as suggested by @BrandonTJones ) and it would conform to the standard set by the zig community.

**Comment by SamTebbs33** [comment]
Agreed on using the established zig code style and @DrDeano 's proposed orderings. As part of this issue, zig fmt should be added as a step in CI and should fail if any non-conforming files are reported. Ordering should be addressed during code review.

**Comment by DrDeano** [comment]
I wasn't sure where to put this, (could go in #63) but need to ensure there are no `catch unreachable` bc will cause undefined behavior in release-fast/small.

**Comment by SamTebbs33** [comment]
> I wasn't sure where to put this, (could go in #63) but need to ensure there are no `catch unreachable` bc will cause undefined behavior in release-fast/small.

I agree that there shouldn't be a `catch unreachable` for code that could fail, but what about code that can't? Kernel panic?

**Comment by DrDeano** [comment]
Yes, I was thinking of just a panic for now, but could come up with smarter solutions in the future.
